<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pharma_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.pharma_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Fortunepharm custom functions module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_query_alter().
 */
function pharma_custom_views_query_alter(Drupal\views\ViewExecutable $view, Drupal\views\Plugin\views\query\QueryPluginBase $query) {
  $path      = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);
  // Condtion start
  if (isset($path_args[1]) && $path_args[1] =='product') {
    if ($view->id() == 'product_content' && $view->getDisplay()->display['id'] == 'page_1') {
      foreach ($query->where as &$condition_group) {
        foreach ($condition_group['conditions'] as &$condition) {
          if (strpos($condition['field'], 'taxonomy_index_tid')) {
            $condition['value'][':taxonomy_index_tid'] = $path_args[3];
          }
        }
      }
    }
  }
  // Condtion End
  // Condtion start - Product content details block
  if (isset($path_args[1]) && $path_args[1] =='product') {
    if ($view->id() == 'product_content' && $view->getDisplay()->display['id'] == 'block_3') {
      foreach ($query->where as &$condition_group) {
        foreach ($condition_group['conditions'] as &$condition) {
          if (strpos($condition['field'], 'taxonomy_index_tid1')) {
            $condition['value'][':taxonomy_index_tid1'] = $path_args[3];
          }
          if (strpos($condition['field'], 'node__field_weight_field_weight_value')) {
            $condition['value'][':node__field_weight_field_weight_value'] = $path_args[4];
          }
        }
      }
    }
  }
  // Condtion End
}
