<?php

use Drupal\Core\Url;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Link;

/**
 * Implements hook_preprocess_region___HOOK().
 */
function pharm_theme_preprocess_region__header(&$vars)
{
  $language         = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $vars['language'] = $language;

  $path                = \Drupal::request()->attributes->get('_system_path');
  $current_uri         = \Drupal::request()->getRequestUri();
  $current_path        = \Drupal::service('path.current')->getPath();
  $result              = \Drupal::service('path.alias_manager')->getAliasByPath($current_path);
  $vars['current_url'] = $result;
  $vars['logopath'] = file_url_transform_relative(file_create_url(theme_get_setting('logo.url')));
}

/**
 * Implements hook_preprocess_block().
 */
function pharm_theme_preprocess_block(&$vars)
{
  $language         = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $vars['language'] = $language;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function pharm_theme_preprocess_html(&$variables)
{
  $path      = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);

  $language         = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $vars['language'] = $language;

  if (isset($path_args[1]) && isset($path_args[2]) && ($path_args[1] == 'node') && (is_numeric($path_args[2]))) {
    $variables['attributes']['class'][] = 'page-node-' . $path_args[2];
  }
  $variables['attributes']['class'][] = 'lang-'.$language;

  $pink_array = [38,42,43];
  $alias = \Drupal::service('path.alias_manager')->getAliasByPath($path);
  if (isset($path_args[1]) && $path_args[1] == 'product') {
    if(in_array($path_args[3], $pink_array)) {
    $variables['attributes']['class'][] = 'children';
    }
    if (strpos($alias,'product') !== false) {
      if($language == 'zh-hans'){
        $variables['head_title']['title'] = '產品';
      } elseif($language == 'zh-hant'){
        $variables['head_title']['title'] = '产品';
      } else $variables['head_title']['title'] = 'Product Content';
    }
  }
  if (strpos($alias,'health-tips') !== false) {
    if($language == 'zh-hans'){
      $variables['head_title']['title'] = '健康資訊';
    } elseif($language == 'zh-hant'){
    $variables['head_title']['title'] = '健康资讯';
    } else $variables['head_title']['title'] = 'Health Tips';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function pharm_theme_preprocess_pager(array &$variables)
{
  // @see globals.api.php
  $path      = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);

  $current_url = Url::fromRoute('<current>');
  $url         = $current_url->toString();

  global $pager_total;
  $element = $variables['pager']['#element'];
  // Get the max page number for the current pager.
  $variables['pager_max'] = $pager_total[$element];
  $variables['arg_one']   = $path_args[1];
  $variables['page_url']  = $url;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function pharm_theme_preprocess_page(array &$variables)
{
  $path      = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);

  $result              = \Drupal::service('path.alias_manager')->getAliasByPath($path);
  $variables['current_url'] = $result;

  $array     = [20];
  if (isset($path_args[1]) && isset($path_args[2]) && ($path_args[1] == 'node')
    && (in_array($path_args[2], $array))) {
    $variables['#attached']['library'][] = 'pharm_theme/loadsh';
  }

  if (isset($path_args[1]) && $path_args[1] == 'node') {
    if ($variables['node']->getType() == "healthtips") {
      $variables['#attached']['library'][] = 'pharm_theme/healthtips';
    }
  }

  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['language'] = $language;

}

/**
 * Implements hook_preprocess_node().
 */
function pharm_theme_preprocess_node(&$variables)
{
  if ($variables['node']->getType() == 'healthtips') {
    $variables['#attached']['library'][] = 'pharm_theme/healthtips';

  }
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function pharm_theme_theme_suggestions_page_alter(array &$suggestions, array $variables)
{
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $content_type = $node->bundle();
    if ($content_type == 'healthtips') {
      $suggestions[] = 'page__' . $content_type;
    }
  }

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $content_type = $node->bundle();
    if ($content_type == 'faq') {
      $suggestions[] = 'page__faq';
    }
  }

  $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);
  if (isset($path_args[1]) && $path_args[1] == 'faq') {
    $suggestions[] = 'page__faq';
  }
  if (isset($path_args[1]) && $path_args[1] == 'product') {
    $suggestions[] = 'page__product';
  }
}

/**
 * Implements hook_preprocess_menu().
 */
function pharm_theme_preprocess_menu(&$variables, $hook) {
  if ($hook == 'menu__main') {
    // Get the current path.
    $current_path = \Drupal::request()->getRequestUri();
    $path_args = explode('/', $current_path);
    $items = $variables['items'];
    foreach ($items as $key => $item) {
      // If path is current_path, set active to li.
      $urlString = $item['url']->toString();
      if ($item['url']->toString() == $current_path) {
        // Add active link.
        $variables['items'][$key]['attributes']['class'] = 'active';
      }

      // Product & Faq - menu add active class
      if (isset($path_args) && isset($path_args[2])){
        $arg = '/'.$path_args[2].'/';
        if (strpos($urlString, $arg) !== false) {
          $variables['items'][$key]['attributes']['class'] = 'active';
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_views_view_list().
 */
function pharm_theme_preprocess_views_view_list(&$variables) {
  $language         = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $variables['language'] = $language;

  $path      = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);
  $variables['parent_url_id'] = $path_args;

  $result = [];
  $parents_term = [];
  $terms = \Drupal::entityManager()->getStorage('taxonomy_term')->loadTree('product');
  foreach ($terms as $term) {
    if ($term->parents[0] !=0) {
      $result[$term->parents[0]][$term->tid] = array(
        "id" => $term->tid,
        "name" => $term->name,
        "parents" => $term->parents[0],
        'weight' => $term->weight
      );
    }
  }
  $variables['child_array'] = $result;

  foreach ($terms as $term) {
    if ($term->parents[0] !=0) {
      $parents_term[$term->tid] = array(
        "parents" => $term->parents[0],
      );
    }
  }
  $variables['parent_array'] = $parents_term;
}
